### ISSUE TITLE
Wisdoms, Part 2; Protonation exchange attempts

### ISSUE THREAD

**Issue by swails** [choderalab/openmm-constph#3]
This part deals with the protonation state change strategy that yields the most efficient sampling of the total semi-grand ensemble.

I've thought about this quite a bit, and I think Amber's approach is about as good as you can do.  To lay the background, Amber attempts to change a random residue's protonation state to a random (but different) state.  Unless two residues are coupled together energetically, attempting two protonation state changes at the same time will hurt the probability of accepting the move.

I'm pretty sure the maximum acceptance probability for the reference compound will occur when the pH is set to the pKa of the residue.  At this point, the model CYS residue (which has 2 protonation states), has a 45% acceptance rate.  Titrating two independent CYS residues will drop that to <25%.  (This code already takes the single-residue approach).  One difference of Amber's is that the multi-state move is attempted between a random residue in the pairlist of the first chosen residue.  I don't think this makes too much of a difference from your approach, but for a large number of residues in a large system it might.

I also think that only attempting one protonation state change per MC attempt is the best way to go.  My argument for this point is not that many change attempts will hurt, just that the simulation becomes less efficient doing that.  In the process of computing the energy of a protonation state, you also get the forces essentially for free.  With those forces in hand, there is little cost in advancing the simulation, and this way you utilize all of the energy calculations for the different trial states.  In my experience, even in typical proteins with 10-20+ titratable residues, protonation state sampling occurs so rapidly that I've always focused on trying to improve conformational sampling.  Most papers that focus on improving CpHMD focus on enhancing conformational sampling for this reason.

**Comment by bas-rustenburg** [comment]
I think we've adopted this strategy as well.
